[package]
name = "hexer"
version = "0.3.0"
edition = "2024"
authors = ["N Lang Team"]
description = "Zero-boilerplate hexagonal architecture with graph-based introspection"
license = "MIT OR Apache-2.0"
keywords = ["hexagonal", "architecture", "ports", "adapters", "ddd"]
categories = ["development-tools", "data-structures"]

[workspace]
members = [".", "hex_macros"]

[dependencies]
inventory = "0.3"
hex_macros = { version = "0.3.0", path = "./hex_macros", optional = true }
serde = { version = "1.0", features = ["derive"], optional = true }
serde_json = { version = "1.0", optional = true }
chrono = { version = "0.4.42", optional = true }
tokio = {  version = "1.47.1", optional = true, features = ["sync", "macros", "rt-multi-thread", "time"] }
async-trait = {version = "0.1.89", optional = true }

[dev-dependencies]
pretty_assertions = "1.4"
tokio = { version = "1.47.1", features = ["sync", "macros", "rt-multi-thread", "time"] }

[features]
default = ["macros"]
macros = ["hex_macros"]
ai = ["chrono"]
async = ["tokio", "async-trait"]
visualization = ["serde", "serde_json"]
container = ["tokio", "async-trait"]
full = ["ai", "async", "macros", "visualization", "container"]

[workspace.dependencies]
syn = { version = "2.0", features = ["full", "extra-traits"] }
quote = "1.0"
proc-macro2 = "1.0"
darling = "0.20"

[package.metadata.docs.rs]
all-features = true
