graph TD
  10412492039965543270["realworld_api::domain::article::Article\n(Entity)"]
  10347384604705785648["realworld_api::adapters::in_memory_db::user_adapter::InMemoryUserRepository\n(Adapter)"]
  20562250797671452["realworld_api::domain::user::User\n(Entity)"]
  7785202712665265961["realworld_api::ports::comment_repository::CommentFilter\n(Repository)"]
  6036380904514364673["realworld_api::ports::user_repository::UserFilter\n(Repository)"]
  4722985126513128954["realworld_api::adapters::in_memory_db::article_adapter::InMemoryArticleRepository\n(Adapter)"]
  10644884200148206392["realworld_api::adapters::in_memory_db::comment_adapter::InMemoryCommentRepository\n(Adapter)"]
  17435541042506597494["realworld_api::ports::article_repository::ArticleSortKey\n(Repository)"]
  14618512971669648406["realworld_api::domain::tag::Tag\n(Entity)"]
  14733129128909500908["realworld_api::ports::user_repository::UserSortKey\n(Repository)"]
  4583760324640920868["realworld_api::domain::comment::Comment\n(Entity)"]
  17104016576760588564["realworld_api::ports::comment_repository::CommentSortKey\n(Repository)"]
  7498128437058494122["realworld_api::adapters::in_memory_db::tag_adapter::InMemoryTagRepository\n(Adapter)"]
  528349728044715595["realworld_api::ports::article_repository::ArticleFilter\n(Repository)"]

